GestorEventos.WebAdmin/Models/ErrorViewModel.cs
namespace GestorEventos.WebAdmin.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

GestorEventos.WebAdmin/Controllers/HomeController.cs
using GestorEventos.WebAdmin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestorEventos.WebAdmin.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

GestorEventos.WebAdmin/Controllers/ServiciosController.cs
using GestorEventos.Servicios.Entidades;
using GestorEventos.Servicios.Servicios;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GestorEventos.WebAdmin.Controllers
{
	public class ServiciosController : Controller
	{

		// GET: ServiciosController
		public ActionResult Index()
		{
			ServicioDeServicios sServicios = new ServicioDeServicios(); 
//			servicioService.GetServicios();

			return View(sServicios.ObtenerServicios());
		}

		// GET: ServiciosController/Details/5
		public ActionResult Details(int id)
		{
            ServicioDeServicios sServicios = new ServicioDeServicios();

            return View(sServicios.ObtenerServicioId(id));
		}

		// GET: ServiciosController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: ServiciosController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
                ServicioDeServicios sServicios = new ServicioDeServicios();

                Servicio servicio = new Servicio();

				servicio.Descripcion = collection["Descripcion"].ToString();
				servicio.PrecioServicio = decimal.Parse(collection["PrecioServicio"].ToString());


				sServicios.AgregarServicio(servicio);


                return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ServiciosController/Edit/5
		public ActionResult Edit(int id)
		{
            ServicioDeServicios sServicios = new ServicioDeServicios();


            return View(sServicios.ObtenerServicioId(id));
        }

		// POST: ServiciosController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
                ServicioDeServicios sServicios = new ServicioDeServicios();

                Servicio servicio = new Servicio();

				servicio.IdServicio = int.Parse(collection["IdServicio"].ToString());
				servicio.Descripcion = collection["Descripcion"].ToString();
				servicio.PrecioServicio = decimal.Parse(collection["PrecioServicio"].ToString());

				sServicios.ModificarServicio(id, servicio);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ServiciosController/Delete/5
		public ActionResult Delete(int id)
		{

            ServicioDeServicios sServicios = new ServicioDeServicios();

			Servicio servicio = sServicios.ObtenerServicioId(id); 

            return View(servicio);
        }

		// POST: ServiciosController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
                ServicioDeServicios sServicios = new ServicioDeServicios();

				sServicios.BorradoLogicoServicio(id);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

GestorEventos.WebAdmin/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sample App</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <header>
        <div class="header_logo">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-alipay" viewBox="0 0 16 16">
                <path d="M2.541 0H13.5a2.55 2.55 0 0 1 2.54 2.563v8.297c-.006 0-.531-.046-2.978-.813-.412-.14-.916-.327-1.479-.536q-.456-.17-.957-.353a13 13 0 0 0 1.325-3.373H8.822V4.649h3.831v-.634h-3.83V2.121H7.26c-.274 0-.274.273-.274.273v1.621H3.11v.634h3.875v1.136h-3.2v.634H9.99c-.227.789-.532 1.53-.894 2.202-2.013-.67-4.161-1.212-5.51-.878-.864.214-1.42.597-1.746.998-1.499 1.84-.424 4.633 2.741 4.633 1.872 0 3.675-1.053 5.072-2.787 2.08 1.008 6.37 2.738 6.387 2.745v.105A2.55 2.55 0 0 1 13.5 16H2.541A2.55 2.55 0 0 1 0 13.437V2.563A2.55 2.55 0 0 1 2.541 0" />
                <path d="M2.309 9.27c-1.22 1.073-.49 3.034 1.978 3.034 1.434 0 2.868-.925 3.994-2.406-1.602-.789-2.959-1.353-4.425-1.207-.397.04-1.14.217-1.547.58Z" />
            </svg>
        </div>
        <nav class="header_nav">
            <ul>
                <li>a</li>
                <li>b</li>
                <li>c</li>
            </ul>
        </nav>
    </header>
    <main id="index_main">
        <section id="index_main_botonera">
            <button class="botoesFetch" data-url="https://localhost:7282/ControladorServicio/ObtenerServicios" data-target="resultServicios" data-type="servicios">Obtener Servicios</button>
            <button class="botoesFetch" data-url="https://localhost:7282/ControladorLocalidad/ObtenerLocalidad" data-target="resultLocalidades" data-type="localidades">Obtener Localidades</button>
            <form id="localidadForm">
                <label for="idLocalidad">ID Localidad:</label>
                <input type="text" id="idLocalidad" name="idLocalidad" required>
                <button class="botoesFetch" type="submit">Obtener Localidad</button>
            </form>
        </section>
        <section id="index_main_resultados">
            <div class="resultados" id="resultLocalidades"></div>
            <div class="resultados" id="resultLocalidad"></div>
            <div class="resultados" id="resultServicios"></div>
        </section>
    </main>
    <script>
        document.querySelectorAll('button[data-url]').forEach(button => {
            button.addEventListener('click', () => {
                const url = button.getAttribute('data-url');
                const target = button.getAttribute('data-target');
                const type = button.getAttribute('data-type');

                fetchDataAndDisplay(url, target, type);
            });
        });

        document.getElementById('localidadForm').addEventListener('submit', event => {
            event.preventDefault();

            document.querySelector("#resultLocalidades").innerHTML = "";
            const idLocalidad = document.getElementById('idLocalidad').value;
            const url = `https://localhost:7282/ControladorLocalidad/ObtenerLocalidad/${idLocalidad}`;
            fetchLocalidad(url, 'resultLocalidad');
        });

        function fetchDataAndDisplay(url, target, type) {
            fetch(url)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('No se pudo conectar con la api');
                    }
                    return response.json();
                })
                .then(data => {
                    console.log(data); // Necesito ver y controlar el json

                    let html = '<ul class="fade-in">';
                    data.forEach(item => {
                        if (type === 'servicios') {
                            html += `
                                <li class="fade-in">
                                    ${item.idServicio} - ${item.descripcion}
                                    <div class="highlight">$${item.precioServicio}</div>
                                </li>
                            `;
                        } else if (type === 'localidades') {
                            document.querySelector("#resultLocalidad").innerHTML = "";
                            html += `
                                <li class="fade-in">
                                    ${item.idLocalidad} - ${item.nombreLocalidad}
                                </li>
                            `;
                        }
                    });
                    html += '</ul>';

                    const resultElement = document.getElementById(target);
                    resultElement.innerHTML = '';
                    resultElement.innerHTML = html;

                    void resultElement.offsetWidth;
                })
                .catch(error => console.error('Error:', error));
        }

        function fetchLocalidad(url, target) {

            fetch(url)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('No se pudo conectar con la api');
                    }
                    return response.json();
                })
                .then(data => {
                    console.log(data);

                    const resultElement = document.getElementById(target);
                    resultElement.innerHTML = '';
                    const html = `
                        <ul class="fade-in">
                            <li class="fade-in">
                                ${data.idLocalidad} - ${data.nombreLocalidad}
                                <div class="highlight"></div>
                            </li>
                        </ul>
                    `;
                    resultElement.innerHTML = html;
                    void resultElement.offsetWidth;
                })
                .catch(error => console.error('Error:', error));
        }
    </script>
</body>
</html>

GestorEventos.WebAdmin/Views/Servicios/Create.cshtml
@model GestorEventos.Servicios.Entidades.Servicio

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nuevo Servicio</h1>

<h4>Servicio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="IdServicio" class="form-control" type="hidden" value="0" />


            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripción</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioServicio" class="control-label">Precio</label>
                <input asp-for="PrecioServicio" class="form-control" />
                <span asp-validation-for="PrecioServicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear servicio" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Atras</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestorEventos.WebAdmin/Views/Servicios/Delete.cshtml
@model GestorEventos.Servicios.Entidades.Servicio

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar Servicio</h1>

<!--<h3>Esta seguro de borrar este servicio?</h3>-->
<div>
    <h4>Detalle del servicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdServicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdServicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioServicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioServicio)
        </dd>
    </dl>
    <h4>Esta seguro de borrar este servicio?</h4>
    <form asp-action="Delete" asp-route-id="@Model.IdServicio">
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Atras</a>
    </form>
</div>

GestorEventos.WebAdmin/Views/Servicios/Details.cshtml
@model GestorEventos.Servicios.Entidades.Servicio

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalle del servicio</h1>

<div>
    <h4>Servicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdServicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdServicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioServicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioServicio)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Editar", new {  id = Model.IdServicio }) |
    <a asp-action="Index">Atras</a>
</div>

GestorEventos.WebAdmin/Views/Servicios/Edit.cshtml
@model GestorEventos.Servicios.Entidades.Servicio

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar Servicio</h1>

<h4>Servicio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.IdServicio">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdServicio" class="control-label"></label>
                <input asp-for="IdServicio" class="form-control" readonly />
                <span asp-validation-for="IdServicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripción</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioServicio" class="control-label">Precio</label>
                <input asp-for="PrecioServicio" class="form-control" />
                <span asp-validation-for="PrecioServicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
     <a asp-action="Index">Atras</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestorEventos.WebAdmin/Views/Servicios/Index.cshtml
@model IEnumerable<GestorEventos.Servicios.Entidades.Servicio>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Listado de servicios</h1>

<p>
    <a asp-action="Create">Nuevo Servicio</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdServicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioServicio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdServicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioServicio)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new {  id=item.IdServicio }) |
                @Html.ActionLink("Detalle", "Details", new { id = item.IdServicio }) |
                @Html.ActionLink("Borrar", "Delete", new {  id=item.IdServicio })
            </td>
        </tr>
}
    </tbody>
</table>

GestorEventos.WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestorEventos.WebAdmin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestorEventos.WebAdmin.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestorEventos.WebAdmin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Servicios" asp-action="Index">Servicios</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GestorEventos.WebAdmin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>